### ISSUE TITLE
www.universal-dependencies.org

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#215] opened 2015-09-29 13:10 UTC
Wouldn't it slowly be the time to grab that domain?

**Comment by spyysalo** [comment] 2015-09-29 14:05
+1 (maybe without the hyphen?)

**Comment by manning** [comment] 2015-10-05 04:08
Yes. :)

**Comment by dan-zeman** [comment] 2015-10-05 06:34
+1

**Comment by spyysalo** [comment] 2016-01-26 21:32
I think it would be appropriate for @jnivre to own this, but I can grab it if it helps.

**Comment by jnivre** [comment] 2016-01-27 08:27
I would be very proud to own this. Maybe without the hyphen?

**Comment by dan-zeman** [comment] 2016-01-27 08:35
I have no opinion whether it is better with or without the hyphen. (It would be good to own both but I have no idea what are the costs, maybe it is not worth it.)

**Comment by spyysalo** [comment] 2016-01-27 14:02
Without the hyphen is my preference too. If nobody objects, perhaps this is enough to move ahead on? It would be nice to have this cleaner URL in the LREC camera-ready.

@jnivre : I'd be very happy to help with the technical side, please email me if I can be of any use in making this happen.

**Comment by jnivre** [comment] 2016-01-27 15:04
@spyysalo I would appreciate any help I can get. I know very little about these things, but I am happy to pay. :)

**Comment by spyysalo** [comment] 2016-01-27 21:20
Check out http://universaldependencies.org/ :-)

@fginter : now we just need to get the content there. The repo is https://github.com/UniversalDependencies/universaldependencies.github.io/ (the name is mandated by GitHub pages), and this should hopefully work just by reconfiguring the jekyll-hook.

**Comment by jnivre** [comment] 2016-01-27 21:22
Does this mean I actually managed the DNS setup correctly? I am truly amazed. :)

**Comment by fginter** [comment] 2016-01-28 12:46
I updated the docs generation scripts and http://universaldependencies.org/ is now live and updated. By some mysterious mechanism, all universaldependencies.github.io traffic gets redirected onto the new domain, so that's a bonus. But all new links please point to http://universaldependencies.org/. I bulk-edited all hard-coded links in the docs to the new place as well. Thanks @spyysalo and @jnivre for getting this done!

**Comment by spyysalo** [comment] 2016-01-28 12:49
Thanks Filip! I'm very happy to close this one, please open new issues if any are caused by the move.

**Closed as completed by spyysalo** 2016-01-28 12:49 UTC
Labels: a:enhancement
