### ISSUE TITLE
Validity of CoNLL-U

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#242] opened 2016-01-19 18:36 UTC
We would like to use CoNLL-U as a data interchange format and define two levels of "validity". The first level (analogy to XML well-fomedness) means that any CoNLLU-conforming tool can read the file. The second level (analogy to DTD validation) means that the file strictly conforms to UD definition for a given language/treebank (including sets of language-specific deprel, feats and misc values).
- [ ] The [CoNLL-U specification](https://universaldependencies.github.io/docs/format.html) does not distinguish any levels of validity.
- [ ] It does not link the [validate.py](https://github.com/UniversalDependencies/tools/blob/master/validate.py) tool.
- [x] It does not mention that only unix-style LF newlines are allowed (but validate.py checks it).
- [x] It does not explicitly forbid UPOS=_ (but validate.py does not allow underscores as UPOS except for multiword tokens).

As for the last point, I though that UPOS=X means a word which cannot be assigned any other part-of-spech category (e.g. code switching), but underscore means an unknown/empty value and it should be used e.g. if no tagger (or human annotator) was applied (yet).

Once the CoNLL-U specification page becomes too long, it would be probably good to move the details to a separate page, so that the main page stays brief.

**Comment by foxik** [comment] 2016-01-19 19:52
The similar issue happens in multiple columns:
- for LEMMA, it makes sense to have `_` as "not assigned" (it is currently used in UD-1.2 fr, for example), but one would have to deal with `_` form which would have `_` as lemam. Note that currently the semantics allow `_` in LEMMA position (as in UD-1.2 fr), but it means "lemma is underscore", instead of "no lemma is assigned"
- for HEAD, it makes sense to have `_` which means "not assigned", versa `0`, which means "assigned to head"
- for DEPREL, which could have `_` value if if HEAD has `_`.

Personally I would vote for allowing _ in LEMMA, UPOS, HEAD and DEPREL (i.e., everywhere but ID and FORM), so that the CoNLL-U format can be used in various stage of the pipeline (i.e., after tokenization, _ will be everywhere but ID and FORM).

Note that multi-word tokens already use this syntax (`_` everywhere but ID and FORM). If CoNLL-U gets widespread, people are going to need "unassigned" mark in my opinion, and my guess is that they will use underscores (as some of the columns allow and also multi-word tokens use). So it would make sense to standardize it.

**Comment by fginter** [comment] 2016-01-19 20:12
ID, UPOS, HEAD, DEPREL are not allowed to be empty ie _. At least not in UD treebanks. If form is _ the lemma will be same. Yes. But this is probably not a problem because it's quite simple to deduce from the form or other lemmas what the underscore means. 

validate.py in tools checks for both forms of validity you mention. It checks the data is structurally ok and it also checks the tagsets are correct for the given language.

**Comment by foxik** [comment] 2016-01-20 12:41
I understand that UPOS, HEAD and DEPREL are not allowed to be empty.

What I propose is to _allow_ them to be "unassigned" or "empty" -- specifically, mention it in the docs at http://universaldependencies.github.io/docs/format.html. Even if UD treebanks themself will not benefit from such possibility, I believe there are important use cases:

We are working on a pipeline which will allow standard operations like tokenization, POS tagging, lemmatization and parsing. We want to use the CoNLL-U format. If the whole pipeline is executed, using CoNLL-U is fine, because we start with plain text and end in CoNLL-U with all data filled in. But it we interrupt the pipeline at some point (after tokenization, or POS tagging), then we need to indicate that some fields are not filled yet. If we cannot do this in CoNLL-U, we will need to develop another format which will allow it (either "updating" CoNLL-U and creating some "extended CoNLL-U" or CoNLL-UE, or using something else altogether).

I believe allowing empty fields (all but ID and FORM) would benefit the CoNLL-U format and "cost nothing" for the UD project itself. For UD treebanks, the rules would probably stay the same (UPOS, HEAD, DEPREL filled); nevertheless, valid CoNLL-U files could contain no UPOS, HEAD, ... . This would allow the CoNLL-U format to be used in various pipelines and contribute to CoNLL-U wider usage.

I also believe that people will be using CoNLL-U-like format for this (representing empty values) anyway, so allowing in the CoNLL-U docs would prevent a situation where people develop different extensions fo the original CoNLL-U format.

Note that I am making distinction between generic CoNLL-U format (which would allow empty values for anything but ID and FORM), and CoNLL-U files of UD treebank (which would probably continue to  require UPOS, HEAD and DEPREL filled).

**Comment by fginter** [comment] 2016-01-20 13:14
Myself I'm totally fine with that. Sure. We could add a `--relaxed` switch to the validator or something such which would allow these to be empty. Then when validating specifically UD data, we would not use it and force `--lang`. I would prefer the default to be strict as we've had some prior mini-disasters with the validator being too permissive by default and broken data sneaking in.

**Comment by foxik** [comment] 2016-01-20 13:23
I agree with the strict default -- I believe the validator is used mainly for UD treebanks, where it is important to check all fields.

I only want the possibility to use the CoNLL-U with empty fields outside of UD treebanks, so using `--relaxed` or something is fine. What I really need is only mentioning the possibility in the description of the format -- we could leave `validate.py` to be UD treebanks validator (or rename it to `validate_ud_treebank.py` and add `validate_generic_conllu.py` of `validate_conllu.py`).

Should I wait for more people to comment on this, or should be perform more bikeshedding, or should I start creating pull requests and we will continue there?

**Comment by martinpopel** [comment] 2016-01-20 13:33
Yes, `--relaxed` sounds reasonable, this is the first level (well-formedness) I mentioned. So maybe also the [CoNLL-U specification](https://universaldependencies.github.io/docs/format.html) should distinguish the two levels: valid (generic) CoNLL-U format file vs. valid UD1.2 treebank content (saved in CoNLL-U file).

Side note: for some use cases (delexicalized parsing, treebank "patches" where the text has a bad licence, but the morpho/syntactic annotation has a nice permissive licence,...) even the FORM may be empty/unassigned. But using underscore as FORM (or LEMMA) is possible already now. Only the semantics is not clear (Is it a sentence where all words are actually underscores?), but I think there is no need to formalize this. It will be clear from the context.

**Comment by fginter** [comment] 2016-01-20 13:37
So I guess if you add something to the effect of "Underscore `_` is used to denote unspecified values in all fields except `ID`, however in UD treebanks the `UPOS`, `HEAD`, `DEPREL` columns are not allowed to be left unspecified" - would that work?

**Comment by fginter** [comment] 2016-01-20 13:40
@martinpopel UD_Japanese is an example. No forms due to licensing issues: [try here](http://bionlp-www.utu.fi/dep_search/?db=Japanese-KTC&search=_+%3Cnsubj+_)

**Comment by foxik** [comment] 2016-01-20 14:00
> So I guess if you add something to the effect of "Underscore _ is used to denote unspecified values in all fields except ID, however in UD treebanks the UPOS, HEAD, DEPREL columns are not allowed to be left unspecified" - would that work?

Yes, that is nearly what I have in mind. The only issue is the FORM and LEMMA field, where `_` is an unavoidable value which we need to represent. Do you have any idea how to handle this? We could:
- leave the semantics unspecified and sat that Undersocre denotes unspecified values in all fields except ID, FORM and LEMMA (probably a way to go)
- we could devise some other representation of empty value for FORM and LEMMA (unpractical and inconsistent)
- we could devise some other representation for underscore in FORM and LEMMA (like two underscores; needs special treatment, would change existing CoNLL-U files -- bad)
- we could say that the underscores mean "no value" in FORM and LEMMA if it is used for all words of a sentence (weird; still would not allow one sentence containing an underscore)
- we could say that `_` has no special meaning for FORM, but it represent unspecified value in LEMMA, except for the case when FORM is `_` and then LEMMA is also `_`.

Any ideas? I would probably go with the last -- no special treatment for FORM, and using it as "unspecified value" for LEMMA, except when FORM is also "_". That has bad semantics for inputs with both FORMs and LEMMAs unspecified, but I see no better alternative without changing existing files (in theory we could say that when FORM and LEMMA are underscores, they are empty, and if they start with underscores, it should be ignored; then FORM equal to "_" could be represented using "__" -- but this is backward incompatible and definitely not a way to go).

On, one last thing -- the original issue contain also other possible changes to docs page -- notably whether other line endings than LF are allowed -- what about using similar formulation "both LF or CR+LF line endings are allowed, however in UD treebanks only LF are used"?

**Comment by fginter** [comment] 2016-01-20 19:48
Yes. I would let the form/lemma underscore thing be as is. Devising some special coding for these would I think cause more trouble than good.

CRLF. I think using only single newline option has lots of advantages. Things like SVN can bite if you happen to change the newline character because they see it as a full line change. So I personally  would leave it as is. But since I'm only in charge of validating the UD data, I'm not going out of my way to oppose. Still, if you ask for opinion, I'd leave it as is. :)

**Comment by martinpopel** [comment] 2016-01-21 01:07
I agree the semantics of underscore as form/lemma can be left unspecified to keep it simple. This means that during serialization to CoNLL-U, an empty string or `None` value (in Python) will be encoded as the underscore, but during deserialization it will be decoded as "_" string (with one character). To decode it as `None`, users will have to provide a special parameter depending on the particular toolkit.

As for the CRLF question, I would slightly prefer to allow LF only, but I am OK with allowing both LF and CRLF (in Python, you'll just use `line.rstrip('\r\n')` instead of `line.rstrip('\n')`). But I don't like "leaving it as is" because now the specification says nothing about newlines, but the validator accepts only LF.

**Comment by fginter** [comment] 2016-01-21 04:40
Oh. Sorry. When I said leave as is I meant LF only. The docs should say that of course.

**Comment by foxik** [comment] 2016-01-21 19:00
Great. So what about modifying the docs in the following way:
- changing
  _Annotations are encoded in plain text files (UTF-8) with three types of lines:_
  to
  _Annotations are encoded in plain text files (UTF-8 using only the LF character as line break) with three types of lines:_
- after the two items
  _Fields must not be empty._
  _Fields must not contain space characters._
  adding
  _Underscore `_` is used to denote unspecified values in all fields except ID, FORM and LEMMA. However, in UD treebanks the UPOSTAG, HEAD, DEPREL columns are not allowed to be left unspecified._

**Comment by dan-zeman** [comment] 2016-01-21 19:23
+1 on @foxik 's proposal.

Maybe add explicitly what we just discussed about FORM and LEMMA?
_An underscore in the FORM and LEMMA fields may mean either an unspecified value or a `_` literal; users must define their own means of distinguishing the two cases if they need it._

**Comment by foxik** [comment] 2016-01-21 19:25
@dan-zeman I was also considering to mention the underscore in FORM and LEMMA, so +1 here :-)

**Comment by fginter** [comment] 2016-01-21 19:29
Ok

**Comment by martinpopel** [comment] 2016-01-21 20:05
ok

**Comment by foxik** [comment] 2016-01-21 20:23
BTW, I was thinking some more about the line endings. Note that disallowing CR+LF line breaks will make it more difficult to generate valid CoNLL-U on Windows, as files opened in text mode use CR+LF automatically. So to create valid CoNLL-U, you will have to open files in binary mode and then manually convert the data to UTF-8 (because binary files do not allow automatic Unicode converters).

This is probably minor/no issue for Python & similar, as these handle the file encoding and file endings themselves (using binary access to the file and performing the rest manually), but when using Windows API more directly (as in C / C++, and looking into Java docs this probably affects Java too as OutputStreamWriter does not seem to be able to change line break character), you have to manually deal with binary files and manually use some UTF-8 encoder.

**Comment by dan-zeman** [comment] 2016-01-21 20:31
A matter of taste, I would say. Unlike other Windows-specific issues, this one can be handled. I'm a Windows user and I use two text editors (Notepad2 and WinEdt), both UTF-8 capable and both permanently set to write LF only.

I have met someone who was creating a CoNLL-U file in Excel, though. But the Excel output required postprocessing anyway.

**Comment by fginter** [comment] 2016-01-21 20:33
I'd stick to LF-only. :)

**Comment by martinpopel** [comment] 2016-01-21 20:40
What about this: "_All tools should accept both LF and CR+LF newlines on input, but produce only LF newlines on the output._"? This should be robust.

**Comment by dan-zeman** [comment] 2016-01-21 20:47
I like it.

**Comment by fginter** [comment] 2016-01-21 21:30
ok

**Comment by foxik** [comment] 2016-01-22 08:24
Personally I am still not convinced. If we are specifying that applications should accept CR+LF, I see no harm in allowing both LF and CR+LF.

My reasons for allowing CR+LF:
- if we want Windows binaries to produce only LF, there will have to be some Windows-specific exceptions in the source. Note that when a text file is opened on Windows, any LF written to the file is _automatically_ converted to CR+LF. To stop this, the file has to be _opened_ in binary mode (or `_setmode` can be used, but that is Windows-specific call and needs Windows file descriptor, so it is usually not offered by language libraries - neither C++ streams nor Java offers it, so the binary mode has to be specified when opening the file).
  
  To makes things worse, not only LF<->CR+LF translation changes for binary files, but also Windows Unicode automatic encoding work only for text files.
  
  Note also that on Windows, standard input and standard output are already opened in text mode when an application starts -- so if you want a tool which reads/writes CoNLL-U from stdin/stdout, it will require platform-specific overrides (and you have to decode/encode UTF8 manually).
- Line breaks have been platform-specific for a long time -- most formats process any valid line break (for example, see XML docs http://www.w3.org/TR/REC-xml/#sec-line-ends ).

What I do not like about @martinpopel formulation is that correct tools _must_ produce LF on output. So how about something like _When processing a CoNLL-U file, both LF and CR+LF newlines should be accepted. When creating a CoNLL-U file, LF line endings are preferred, but CR+LF can also be used._

**Comment by martinpopel** [comment] 2016-01-22 08:59
OK, @foxik convinced me (but I had no real preference to start with, I just wanted the specification to be consistent with the validator). I agree that if _all_ tools accept both CR+LF and LF on input, there is no point in preferring LF on output. (My motivation was that there are already some tools which handle only LF newlines, that is they leave the CR as part of MISC, but this is easy to fix. Definitely much easier than convincing C++/Java on Windows to produce UTF8 with LF as @foxik has explained.)

**Comment by fginter** [comment] 2016-01-22 10:08
Well. Originally CoNLL-U has been standardized with LF newlines. We discussed it back then, this was the result for a number of reasons, especially to avoid problems in line-for-line comparison use cases. I do not personally see a particularly compelling need to change this. I would still like to stick with LF, as was the original specs. But I am repeating myself. :)

**Comment by spyysalo** [comment] 2016-01-22 10:11
My vote is for sticking to LF only.
- The validator is the practical definition of the format (as was decided early), so the issue is really just that the documentation has been incomplete.
- No issues have risen so far from this constraint, and all existing UD data follows it.
- Loosening the format now will break existing UD-supporting software in unpredictable ways.

**Comment by fginter** [comment] 2016-01-22 10:17
Thanks for the vote @spyysalo. So @dan-zeman @spyysalo and me all expressed the "let's stay with LF as was the original definition of the format". I think we could close this now.

**Comment by spyysalo** [comment] 2016-01-22 10:19
With all due respect to the carefully considered points presented here, the newline issue is looking a lot like bikeshedding to me (https://en.wikipedia.org/wiki/Law_of_triviality). Agree to close, please open new issues for any separate subissues of the original that may remain unresolved.

**Closed as completed by spyysalo** 2016-01-22 10:19 UTC
Labels: b:CoNLL-U

**Comment by foxik** [comment] 2016-01-22 10:22
There seem to be clear consensus that the LF-only line endings are already standardized (which I did not know about, I could not find it on http://universaldependencies.github.io/docs/format.html -- is there any other CoNLL-U format description?) and that the issue was discussed in the past.

In that case, allowing CR+LF is much bigger change (because some tools were already developed assuming LF line endings only) for little gain (less technical issues). Therefore I retract the CR+LF possibility.

So we are back at the proposal we had before I started this CR+LF question? I repeat it to be on the safe side:
- changing
  _Annotations are encoded in plain text files (UTF-8) with three types of lines:_
  to
  _Annotations are encoded in plain text files (UTF-8 using only the LF character as line break) with three types of lines:_
- after the two items
  _Fields must not be empty._
  _Fields must not contain space characters._
  adding
  _Underscore `_` is used to denote unspecified values in all fields except ID, FORM and LEMMA. However, in UD treebanks the UPOSTAG, HEAD, DEPREL columns are not allowed to be left unspecified._

**Comment by fginter** [comment] 2016-01-22 10:33
`_` is used to denote unspecified values in LEMMA in most of the UD treebanks, and for Japanese also in the FORM. So if you want to be super-precise, I guess "Underscore _ is used to denote unspecified values in all fields except ID. Note that no format-level distinction is made for the rare cases where the FORM or LEMMA is the literal string `_` - processing in such cases is application-dependent. Further, in UD treebanks the UPOSTAG, HEAD, and DEPREL columns are not allowed to be left unspecified.
