### ISSUE TITLE
Status of Subcat

### ISSUE THREAD

**Issue by maartenpt** [UniversalDependencies/docs#808] opened 2021-08-24 10:56 UTC
What is the status of the Subcat feature in UD? It is listed on https://universaldependencies.org/u/feat/index.html - but not as either a lexical feature or a inflectional feature; and on the feature page, it implicitly suggests it would be a "commonly used" feature and even explicitly has a description in a couple of languages ( [af] [ess] [hy] [quc] [u] ). But if you look at the stats.xml pages, there are in fact only 4 treebanks in 3 languages that use it (in 2.6, and of which only Afrikaans coincides) : UD_Afrikaans-AfriBooms, UD_Armenian-ArmTDP, UD_Mbya_Guarani-Dooley, and UD_Mbya_Guarani-Thomas. That is also in line with my feeling/experience, given that this type of syntax is not I would say typically captured in tags, but rather derived from the tree structure; but is that just practice and would UD rather see all treebanks have Subcat, or is Subcat rather a non-recommended feature, or something in the middle?

**Comment by dan-zeman** [comment] 2021-08-27 08:44
`Subcat` is a language-specific feature (regardless of the fact that it could find use in many languages; it simply means that it is not one of the “universal” features in UD). It should not be listed at [https://universaldependencies.org/u/feat/index.html](https://universaldependencies.org/u/feat/index.html); it is listed there by error.

The cause of the error is that even some non-universal features now have a globally accessible documentation page (which can still be overridden by a language-specific page), and an old Jekyll directive generated the alphabetical listing by collecting all documentation pages it found. I think the alphabetical listing is obsolete, as there is a longer alphabetical listing with values and synonyms directly in the table. I will remove it and close the issue.

**Comment by dan-zeman** [comment] 2021-08-27 08:47
Fixed.

**Closed as completed by dan-zeman** 2021-08-27 08:47 UTC
Labels: b:features, b:universal, b:website
