### ISSUE TITLE
Gloss and transliteration

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#514] opened 2017-12-17 17:54 UTC
Currently, glosses and translitterations are considered as marginal features in the UD format (CoNLL-U), as well as in the UD guidelines. See http://universaldependencies.org/format.html#other-miscellaneous-attributes. There are optional MISC attributes and as said in the guidelines "The final MISC field is for storing any additional information that does not fit into any of the other fields". But gloss is generally the first piece of information added to a corpus when one works on a language which is not one of the few languages spoken all around the world. We know that UD has been developped at the begining by computer scientists interested by parsing, but the audience of the project is now becoming much larger than that and many projects of treebanking which are not directly concerned by parsing are joining UD. For such projects, gloss is not peripheral information. Even in the current UD guidelines, it is strange not to have an aligned gloss with the numerous examples which are not in English. I think it is time to face the question.

**Comment by dan-zeman** [comment] 2017-12-17 17:59
Note: three initial comments pertaining to this thread appeared in https://github.com/UniversalDependencies/docs/issues/513#issuecomment-352270767

**Comment by sylvainkahane** [comment] 2018-01-02 14:02
I would to come back to my first message which contained two questions and to reformulate the first question. Concerning translitteration and gloss, there are well established conventions which consist to align them with the text (see the [Glossing Rules of the Max Planck Institute](https://www.eva.mpg.de/lingua/resources/glossing-rules.php)). Would it be possible to have a new presentation for the examples on the UD site (as well as the query tools) that displays the translitterations and glosses when they are present in the Conll-U and align them with the text? It would be nice also if the translation come also from the Conll-U.

**Comment by dan-zeman** [comment] 2018-01-02 14:15
@sylvainkahane : The visualization question has actually been already asked and it is one of our longest open issues, here: https://github.com/UniversalDependencies/docs/issues/13

The problem is that UD infrastructure relies on Brat visualization, therefore the new feature would have to be implemented there. @spyysalo, do you know about any new development of this?

**Comment by martinpopel** [comment] 2018-01-02 14:30
I am not sure what is the goal of this issue (how to make transliterations, glosses and translations "less marginal"):
* Improve guidelines for storing transliterations, glosses and translations in the CoNLL-U format. I think this is already done for transliterations and glosses. For translations (of the whole sentence), some treebanks use a sentence-level comment `english_text` (in addition to the compulsory comment `text` for a plaintext sentence in the original language). I agree the name of this attribute (`english_text` or `en_text` or just `translation`) could be mentioned in the guidelines, so all the (visualization) tools can use it if available.
* Create UD guidelines for glossing. Here we could reuse e.g. the Max Planck Institute's rules or let each treebank to decide what is the most useful (and reachable) way. I think there is no need for duplicating the info from FEATS (e.g. DAT.SG) also in the gloss.
* Add transliterations, glosses and translations to as many UD treebanks as possible. That would be nice, but that's a lot of work:-). Transliterations could be automated in most cases.
* Improve visualization tools (Brat), see https://github.com/UniversalDependencies/docs/issues/13

**Comment by dan-zeman** [comment] 2018-11-13 07:12
The guidelines already exist in http://universaldependencies.org/format.html#miscellaneous so I am closing this issue.

**Closed as completed by dan-zeman** 2018-11-13 07:12 UTC
Labels: b:CoNLL-U, b:website
