### ISSUE TITLE
Treatment of reported speech

### ISSUE THREAD

**Issue by liljao** [UniversalDependencies/docs#261] opened 2016-02-16 14:19 UTC
The treatment of reported speech varies in the Germanic treebanks.

For a sentence like _The guy left early in the morning, John said_:
- Danish and English: have _said_ as root
- Swedish and Norwegian: have '_said_ as parataxis

According to the guidelines, this should be parataxis.

**Comment by jnivre** [comment] 2016-04-11 16:22
Does anyone want to argue that this is not a bug in Danish and English? Or can we close it and let people make the necessary changes?

**Comment by MagaliDuran** [comment] 2022-04-29 20:06
Hello!
We happen to find divergence between two instructions in the Guidelines for annotating Reported Speech:
https://universaldependencies.org/u/overview/specific-syntax.html#paratactic-constructions
https://universaldependencies.org/u/dep/index.html
Could you please check which one is to be followed and unify them?

**Comment by MagaliDuran** [comment] 2022-04-29 21:32
Sorry, the second link is: https://universaldependencies.org/u/dep/ccomp.html

**Comment by nschneid** [comment] 2022-04-30 15:52
Thanks @MagaliDuran, the policy was recently changed but not fully updated in the guidelines.

https://universaldependencies.org/u/dep/ccomp.html#reported-speech is the new policy. To the original question, _The guy left early in the morning, John said_ should have "said" as the root and "left" attaching to it as `ccomp`.

**Closed as completed** 2022-04-30 15:53 UTC
Labels: a:bug, lang:English, b:dependencies, lang:Danish, lang:Germanic

**Comment by MagaliDuran** [comment] 2022-04-30 17:03
Thanks a lot, Nathan!

Em sáb, 30 de abr de 2022 12:53, Nathan Schneider ***@***.***>
escreveu:

**Comment by sylvainkahane** [comment] 2022-04-30 17:11
I think that _John said_ is an insert in (1) _The guy left early in the morning, John said_, because it can be moved:

(2) _The guy, John said, left early in the morning_

I don't think it is a good idea to have two completely different analyses for the two sentences.

For (3) _John said: the guy left early in the morning_, I agree that _said_ must be the head and that the reported speech must be `ccomp`.

The contrast between the two constructions can be shown with the negation. If you answer "_I don't think it is true_", for (3) it means: 'John didn't say that', but for (1) and (2), it rather means: 'the guy didn't leave'.

Additional remark: in French, inserts have a very special property: the subject must be inverted.

_le type est parti tôt ce matin, a dit John_
_le type, a dit John, est parti tôt ce matin_

In our treebanks for spoken French, inserts are analysed as `parataxis:insert`.

**Comment by nschneid** [comment] 2022-04-30 18:16
I agree that in terms of the meaning, placing "John said" at the end backgrounds the attribution, whereas "John said that..." puts the speech event center stage. And a fuller accounting of syntax could distinguish various reported speech constructions within a language.

But in terms of a UD analysis, all of these are broadly similar:

- John said, "Let me go!"
- "Let me go!", John said.
- "Let me go!" said John.

It is straightforward to think of the speech content as licensed by the speech verb (hence `ccomp`).

Our conclusion was to use `parataxis` only if absolutely necessary because the speech verb is inserted within the content.

**Comment by Stormur** [comment] 2022-05-04 17:28
Could it be sensible to officially add a subrelation like `reported` to distinguish between these flavours of `ccomp`?

Similarities are clear, but still, morphosyntactically, I feel they can be quite distinguished: a "true" `ccomp` usually entails some means to signal the embedding of the clause, while "reported `ccomp`s" often are abrupt juxtapositions. So:

- _Ha detto che sarebbe passata_ 'she said she would have come by' - complementiser, irrealis in the verb, adjusted tense

vs.

- _Ha detto "passerò"_ 'She said "I'll come by"' - juxtaposition and e.g. non corresponding tenses
