### ISSUE TITLE
Structures with "dative subject" and "adverb" in Russian

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#248] opened 2016-02-05 12:23 UTC
Hello all, I'm looking at Russian and am curious how UD suggests to deal with structures such as:

```
1  Мне         я          PRON      Case=Dat
2  холодно     холодно    ADV       _
3  .           .          PUNCT     _

1  Мне         я          PRON      Case=Dat
2  было        быть       VERB      Tense=Past
3  холодно     холодно    ADV       _
4  .           .          PUNCT     _
```

Would something like the following be ok:

```
1  Мне         я          PRON      Case=Dat    2    nsubj
2  холодно     холодно    ADV       _           0    root
3  .           .          PUNCT     _           2    punct

1  Мне         я          PRON      Case=Dat    3    nsubj
2  было        быть       VERB      Tense=Past  3    cop
3  холодно     холодно    ADV       _           0    root
4  .           .          PUNCT     _           3    punct
```

I imagine a similar structure exists in Czech and other Slavic languages, but I cannot find it described.

**Comment by dan-zeman** [comment] 2016-02-05 12:42
For Czech it's not described because we did not change the original Prague annotation (except for translating the labels). Check this query:

http://hdl.handle.net/11346/PMLTQ-N0OS

I am not particularly fond of the prospect of having non-nominative subjects, but it actually happens more than by chance, see here:

http://hdl.handle.net/11346/PMLTQ-WAKH

So we've got inconsistency here, thanks for reporting :)

**Comment by dan-zeman** [comment] 2016-02-05 13:00
BTW the original annotation does not mark the adverb as a "nominal predicate" (because it's an adverb), hence our conversion procedure does not treat the verb _to be_ as copula. If dative subjects are allowed then @ftyers 's proposal makes sense to me, but it will be difficult to correct the Czech cases that violate it. Sometimes there may be two adverbs attached to _to be_, such as in:

_Je tomu.Dat skutečně/ADV tak/ADV?_ lit. _Is it.Dat really/ADV so/ADV?_

Human editing seems unavoidable if the "root" adverb is to be identified. But anyway, difficulty with converting existing data should not be the main factor in designing the guidelines. Let's see what others think about this.

**Comment by jnivre** [comment] 2016-02-09 12:40
I can't follow the discussion about the Russian/Czech examples, but as a general principle there is nothing wrong with dative subjects. Our notion of core arguments makes no assumptions about case marking, so nsubj is a priori compatible with any (morphological) case marking. Turkish, for example, consistently has the subject in the genitive in complement clauses.

**Comment by dan-zeman** [comment] 2016-02-09 17:52
It is clear that such a rule could not be universal. It would not be a simple rule either: even Czech grammar admits, in certain contexts, subject in the genitive (although nominative is the default). Anyway, this is an interesting issue that we should try to standardize in the Slavic languages. I think the dative can also be analyzed as an object. But I would like to hear more opinions on that.

**Comment by sjut** [comment] 2016-02-09 20:10
Hello! I am dealing with annotation of syntax relations in Russian. I have some comments on Russian. 
1. There are certain theoretical approaches where Datives are subjects in the constructions with predicatives and with "reflexive" verbs such as "xotet'sya" 'to want' in "mne hochet-sya" - 'I.Dat want-refl' - 'I would like'. There is an evidence that these Datives have some formal Subject properties. They control reflexive pronouns. As nominative Subjects they can control the converbs (there is a rule in Russian that only nominative subjects can be coindexed with "zero subjects" in Converb construction (control the "zero subjects" in converb constructions)). So, they meet certain formal criteria for Subjecthood.
2. Genitives of negation or genitives of quantity like in 'hleba ne xvatilo' - 'bread.GEN NEG were.enough' ('There was lack of bread') have no such properties. However, in the Gold Standard Russian corpus they are treated as Subjects.
3. The modal words like 'mozchno' ('it is possible/it is allowed'), 'nuzchno' ('is needed') as well as special forms like 'xolodno' ('it is cold') etc. do not behave like adverbs (though the later look like adverbs). They control Dative subjects and they are not verb modifiers or sentential modifiers. It's very strange and inconvenient to treat them like adverbs. This could be a source of extra ambiguity in syntactic analysis.
Some pos-taggers have special tag for 'predicatives'  in Russian.

**Comment by ftyers** [comment] 2016-02-09 21:16
I agree with @jnivre that nominative/non-nominative should not be the only criterion for subjecthood. There are plenty of languages where formal subjects are not in nominative case.

@dan-zeman: I believe Serbo-Croatian works similarly "hladno mi je." --- so yes, a pan-Slavic standard would be a good idea.

@sjut: Could you give an example for when you have хотеться in verbal adverb form ? 

In (2) note that you can also (I think) throw a dative in here too for  "когда людям не хватает хлеба..." (when people don't have enough bread). Also, further note, changing the polarity does not change the case of хлеба "нам хватает хлеба, а вам нет" (we have enough bread, but you don't)

A further aside, you also have things like that ("genitive subjects") in habitative constructions like: 

```
у нас была машина, у нас был дом, у нас были друзья
at us  was.F car.F, at us was.M house.M, at us were.Pl friends.Pl

у нас не было машины, у нас не было дома, у нас не было друзей
at us not was.Nt car.Gen, at us not was.Nt house.Gen, at us not was.Nt friends.Pl.Gen
```

In (3), this could be considered partly a result of short form neuter adjectives having the same form as adverbs. As a non-Russian speaker it sometimes feels like what you have is a copula expression, which in English would have an explicit subject "It was cold" (было холодно; can you say "это было холодно"[?]), and then when you want to add the experiencer, it must be in the dative "It was cold to me" (мне было холодно). I feel like you can do a similar thing in Spanish with "me hace frío" ([It] does cold to.me); of course "eso me hace frío" sounds ok in Spanish, but "это мне холодно" does not in Russian. So, it's like, adding the dative means that other subjects are not possible.

One final thing (regarding the predicative part of speech), there is contrast between:

```
1) Я был холоден.         "I was cold" (like emotionally cold)
2) Мне было холодно.  "I felt cold"
```

(I'm not sure if this has made things clearer or less clear, but at least there are some more data points out there) :)

**Comment by sjut** [comment] 2016-02-09 22:05
Maybe, the "хлеб" example is not a good one for iilustrating the construction of gentitve of negation. There are constrcutions as: "Волков (Gen) не водится в этом лесу" "There is no wolves (Gen) in this forest" (see B. Partee etc.). There is no possibility to add Dative or Dummy subject. We just have a Genitive countepart in Negative predication to the Nominative case in positive one.

As for datives. You are right. For the predicative constructions with datives there is no possibility or evidence for "zero" or a trace for additional non-dative subject.  
For the "adverb"-like forms - there are three different syntactic patterns: 
(1) Он весело играет 
      He joifully.Adv play
(2) Он весел - Это весело  
      He.M joyful.M - this.N joyful.N
(3) Мне весело
      I.DAT is.joyful
(4) Мне холодно гулять ... \* Мне это холодно гулять" 
     I.DAT is.cold  to.walk    -  \* I.DAT this cold to.walk
In (1) весело is an Adverb. It modifiers a notional verb (it is a modifier in VP (and not in TP etc.))
In (2) it is a contracted form of an Adjective. It agrees with the subject in gender and number
In (3) it is a predicative. There is no "position" in the sentence for a Nominative subject (even zero subject). The predicative assigns Dative to the Experiencer subject. The Dative here has the Subject properties like in "Мне стыдно за себя" "Мне весело из-за своих ..." etc. 
(4) - in constrcution like (3) it is impossible to have an expletive construction like "это холодно..."
For "хотеться" I didn't mean "verbal adverb" form. There is a class of verbs that trigger dative subjects like хотеться - мне хочется (I.DAT want), нравиться - мне нравится 'I.DAT like' etc.

PS
1) There is also a theoretical approach to infinival constructions for Russian where it is considered that infinitive triggers PRO in Dative like in "Он велел мне [PRO сделать это самому]" - He oredered me [PRO.DAT do this myself] - reflexive quantifier "самому" is controlled by PRO in Dative.
2) It is typologically not a rare situation when we have a special case assignment to experincer verbs and the verb assigns the dative to the Experiencer (e.g. Daghestanina languages, some verbs in some Finno-Ugric languages etc.).

**Comment by simonkrek** [comment] 2016-02-09 22:21
In the canonical Slovenian grammar, similar cases with dative are called "logical subjects", however, in our treebank they are treated as objects. E.g. se ji.DAT je sanjalo ('(it) dreamt to her', see line 14). 

13  se  se  PRON    17  expl    _   Dep=17|Rel=PPart
14  ji  on  PRON    17  iobj    _   Dep=17|Rel=Obj
15  je  biti    AUX     17  aux _   Dep=17|Rel=PPart
17  sanjalo sanjati VERB    0   root    _   

In contrast, negation in Slovenian requires the change of case from nominative to genitive and these cases are treated as subjects, e.g. pravične porazdelitve.GEN ni ('there is no fair distribution', see line 2):

1   Pravične   pravičen   ADJ 2   amod    _   Dep=2|Rel=Atr
2   porazdelitve    porazdelitev    NOUN    3   nsubj   _   Dep=3|Rel=Sb
3   ni  biti    VERB    0   root    _   SpaceAfter=No|Dep=0|Rel=Root

In general, the principle was to avoid non-nominative subjects (except negation), since we identify  'logical subjects' (e.g. in dative) as Agents on the Semantic Role Labeling level.

**Comment by osenova** [comment] 2016-02-09 22:23
In the Bulgarian tradition the subject is nominative as a rule.
In dative structures the datives are considered indirect objects.
We have in Bulgarian the example, given by Francis for Serbo-Croatian: "hladno mi je."/ хладно ми е.
We consider such constructions impersonal with dative indirect objects.

**Comment by jnivre** [comment] 2016-02-09 22:51
Just to clarify: I am not advocating a view of subject that is based on semantic roles. Subject is a grammatical notion that has to be identified using grammatical criteria, such as subject-verb agreement. And for some languages, this notion may coincide perfectly with a particular grammatical case, but there are clearly also languages where this is not the case. 

Note also that the non-criterial status of case holds also for objects. If a verb has two core dependents, then the one that is not the subject should be labeled dobj, regardless of whether it is in accusative or dative. There cannot be an indirect object without a direct object.

**Comment by mojgan-seraji** [comment] 2016-02-09 22:55
Dative subjects have been marked as nsubj:nc (nominal subject: non-canonical) in the Persian_UD.

In Persian, non-canonical subjects appear in dative-subject constructions. In such case, the verb, which normally inflects for number and person with the subject, always stays in third person singular instead and never agrees with the dative subject. Dative subjects often appear as pronominal clitics attached to the complement of the verb. 

‪Form:          (man)     sard-am           hast
‪Gloss:          (I)          cold-pc.1sg      be.pres.3sg ‬
‪Translation:  I am cold

Another example without a copula verb would be:

Form :          (ma)      xoš-emām             mi-āy-ad
‪Gloss :          (we)      well-pc.1pl           cont-come.pres-3sg
Translation:   we like it - it comes us well

**Comment by mojgan-seraji** [comment] 2016-02-09 23:03
Just one clarification: the pronominal clitics have been separated in the Persian UD.

**Comment by jnivre** [comment] 2016-02-09 23:25
It looks to me like we have inconsistent analyses here. Without knowing all the facts, it looks to me like the Bulgarian and Persian cases are rather similar, with an impersonal construction and an oblique argument that has some semantic resemblance to a subject. Yet, in one case the argument is analysed as "iobj" and in the other as "nsubj". Moreover, I think it could be argued that they should neither be "iobj" nor "nsubj" but "dobj", because they are the single non-subject core dependent. I think the term "dobj" is a little unfortunate here, and I think many people would find it less objectionable to use simply "obj" for the second core dependent (regardless of case). Perhaps we should consider moving to Dixon's terminology with "object" and "extended object" instead of "direct object" and "indirect object" in future versions.

**Comment by ftyers** [comment] 2016-02-10 13:49
@sjut 

> (4) - in constrcution like (3) it is impossible to have an expletive construction like "это холодно..."
> For "хотеться" I didn't mean "verbal adverb" form. There is a class of verbs that trigger dative subjects like хотеться - мне хочется (I.DAT want), нравиться - мне нравится 'I.DAT like' etc

At least for нравиться I would be wary of calling мне a subject here, as there is subject agreement with what is liked "мне нравятся эти люди" (I like these people) / "мне нравится это" (I like this) / "ты мне нравишься" (?, I like you) ... much like with "gustar" in Spanish. With хочется it is not the same, as an impersonal you cannot conjugate it for other persons/numbers.

**Comment by sjut** [comment] 2016-02-10 17:21
As for "нравиться, here we have the same situation as for predicatives. We have two (three) different constructions: Мне хочется спать N.Dat Verb+Refl Inf and N.Dat Verb+Refl N.Nom.

As for Subjecthood.
There are syntactic criteria for Subjecthood: structural priority. NP in Subject position should c-command agreement (not only verb agreement, it might be floating quantifier agreement, adjectival predicate agreement) and reflexive pronoun (thouth there are languages with subject-object agreement). If there are some constraints in a language for non-finite constructions it must trigger the control (and some other features of priority). The features are language dependent. However, these are syntactic criteria, not morphological or semantic.

In Russian we have: (1) finite verb-agreement, (2) case assignment for "canonic" nominative Subject. 
However, there are some other features: (3) Reflexive pronoun local binding (c-command) Мне(Dat) стыдно(Predicative) за себя (Refl), Мне(Dat) не думается(Verb+Refl) о себе(Refl), (4) converb construction control (?? ZERO(i) Узнав(Conv) о том, ..., мне(Dat(i)) нужно), (5) floating quantifiers agreement Ей.F+Sg+Dat весело(Predicative) одной(Quantifier.Fem+Sg) '~She is joiful when alone' Ему.M+Sg+Dat весело(Predicative) одному(M+Sg), (6) conjunction reduction Мне холодно и нужно ... (~ I am cold and (zero) need...). (7) purpose construction with the conjunction чтобы 'in order to / to' (this criteria works even if we have nominative NP: Чтобы быть веселым мне нужно выспаться 'In oreder to be joiful I need to sleep' Чтобы быть чистым мне нужно мыло 'In order to be clean I need a piece of soap') 
There are some other features of structural priority as well.  Dative has not all but a certain bulk of features of structural priority (some control features)

**Comment by dan-zeman** [comment] 2016-02-15 21:37
@sjut : Adverbs vs. predicatives: The corresponding Czech words _možno_ (possible), _třeba_ (needed) are tagged `ADJ`. However, _chladno_ (cold) is tagged `ADV`, although it could also be a form of the adjective _chladný._ There are no instances of _Mně bylo chladno._ in the treebank, although the sentence is perfectly grammatical. There is an “existential” example without the dative pronoun: _Večer bývá chladno a větrno._ lit. _Evenings usually-is cold and windy._ Both _chladno_ and _větrno_ are analyzed as adverbial modifiers of the root verb _bývá_.

@ftyers : _Ono mně bylo chladno_ is possible in Czech, although the pronoun is just expletive here.

@simonkrek : Czech equivalent of _se ji je sanjalo_ would be _zdálo se jí_ and it would be annotated similarly, we just use `dobj` instead of `iobj` here, see [http://hdl.handle.net/11346/PMLTQ-WQZC](http://hdl.handle.net/11346/PMLTQ-WQZC).

@sjut : I do not agree that the dative arguments in _мне хочется_ or _мне нравится_ are subjects. In _мне нравится,_ there is a nominative argument that is the subject. In Czech (actual example from the corpus): _to se mi líbí_ (lit. it itself to-me is-liked) … _to_ is nominative / nsubj, _mi_ is dative / dobj. Similarly, for _хотеться / chtít se,_ we (may) have a clausal subject; in addition, the whole construction is analyzed as reflexive passive. (See http://hdl.handle.net/11346/PMLTQ-D5TB.) Example: _nechtělo se mu odpovídat_ “he did not want to answer”:

<pre>1  nechtělo   chtít      VERB  _  Gender=Neut|Number=Sing|Tense=Past|VerbForm=Part  0  root  _  not-want
2  se         se         PRON  _  Case=Acc|Reflex=Yes    1  auxpass:reflex  _  itself
3  mu         on         PRON  _  Case=Dat               1  dobj            _  him
4  odpovídat  odpovídat  VERB  _  VerbForm=Inf           1  csubj           _  to-answer</pre>

As for the structural arguments for subjecthood in your last comment, at least (3) and (4) seem to be valid arguments to me, at least in Russian. I do not think they would work in Czech, though (not with the dative).

**Comment by dan-zeman** [comment] 2016-02-15 21:41
I also had a short look at the treebanks of the remaining two Slavic languages we already have.

Croatian (@zeljkoagic): I found only three instances of `nsubj + Case=Dat`. Two seem to be clear annotation errors. The third one is less clear: _velikom broju ljudi postaje neugodno_ “a lot of people find it uncomfortable” (lot of people is in dative but it is labeled `nsubj`). In contrast, I found an example of dative + adverb: _im je žao onih prosvjednika_ “they are sorry for those protesters”; lit. to-them.Dat is sorry for-those protesters.Loc. The dative pronoun is attached as `iobj`, _je_ is `cop`, _prosvjednika_ is `dobj`, _žao_ is the root.

Old Church Slavonic (@daghaug): Dative subjects exist in a number that is hardly explainable by chance. Unfortunately I do not feel qualified to judge how they compare to what we see in the other Slavic languages.

**Comment by dan-zeman** [comment] 2016-02-15 22:18
I think this thread is ripe to summarize. In the beginning, @ftyers asked how UD analyzes structures like _Мне было холодно._ lit. “to-me it-was cold.” The answer for most Slavic languages currently present in UD (except Old Church Slavonic) is that we do not label dative nominals as subjects because 1. the canonical grammar does not support it, and 2. arguments for doing so would be rather semantic, and UD (at least in its current version) explicitly avoids semantic role labeling. However, @sjut brought up some arguments that are not semantic; these tests may not work in all Slavic languages but they do in Russian.

The dative arguments are treated as objects. However, as pointed by @jnivre, we need to improve cross-language consistency here. In some treebanks the dative object is always labeled `iobj` but the UD guidelines only allow an `iobj` if there is also a `dobj` or `ccomp` or `xcomp`. Otherwise the object is supposed to be `dobj`.

In addition, two other issues have been raised during the discussion.

First, @sjut pointed out that predicative words like _можно_ (possible), _нужно_ (needed) or _холодно_ (cold) do not behave like adverbs. Some equivalents are currently tagged `ADV` in the existing Slavic UD treebanks, although the same reproach may apply to them. Others are tagged `ADJ`, which is probably the only other option in UD, and arguably a good one (the words morphologically match short ("nominal") neuter forms of adjectives, and adjectives are rutinely used as predicates in UD, with copula where applicable).

Second, many Slavic languages allow or even require subject to be in the genitive under certain circumstances (negative existential clauses, partitive, quantity). Unlike the datives discussed above, these genitives are labeled `nsubj` in several treebanks.

I am now tentatively closing this issue, as it seems that the original question has been more or less answered.

**Comment by daghaug** [comment] 2016-02-15 22:38
Sorry to reopen the question just after it was closed, but since the 
issue of OCS was brought up, I thought I'd just say that there are a 
couple of frequent non-finite structures (infinitives, absolute 
participles) that require a dative subject in this language. This has 
nothing to do with particular verbs selecting for dative subjects, it's 
a constructional effect. I don't think there is any convincing evidence 
for real dative subjects (with finite verbs) in OCS. I see there is one 
instance in our treebank, but it's due to an error in the conversion 
procedure.

Dag

**Comment by mojgan-seraji** [comment] 2016-02-16 10:30
It doesn't seem that UD explicitly avoids semantics. So far UD has nicely supported LVCs, with their underlying syntactic structures hand-in-hand with semantics. If UD chooses to go for pure syntax then the entire Persian verbal system will be collapsed (as LVCs are pervasive in the language). Let's have a look at the following example:

Form (transcribed):  Sam       zamin          xord-ø.
Gloss:                       Sam        floor           eat.past-3sg.
Translation:              Sam fell down.

Avoiding semantics in the above example, makes the "floor" to be the direct object. In other words, "Sam" should literally have been eaten the floor. But is that really what UD supports? Although the verb "eat" is normally used as a main verb in Persian, in some cases, it functions as a light verb with a more abstract semantic interpretation and the above example is one such case.

# And when it comes to the dative subject: 

In Persian, verbs normally agree in person and number with their subject. However, there are number of cases where the verb does not agree with its subject, such as:
- in polite usage (Mr. President ARE here / my mother SAID-3pl) 
- plural inanimate subject (The votes IS counted) 
- when making a humble reference to oneself (The servant AM here to help / the servant SAY-1sg)
- non-canonical subject / dative subject (example below)

Form (transcribed):   (man)       az      in       xoš        -am            mi-āy-ad
‪Gloss:                         (I)            of      this     well       -pc.1sg       cont-come.pres-3sg  
Translation:                 I like this 

With the view of identifying subject purely based on grammatical criteria without involving semantic roles, leads Persian to the phase of "subject identity crisis" in the following examples:

A - Mr. President ARE here / my mother SAID-3pl 
B - The votes IS counted
C - The servant AM here to help / the servant SAY-1sg
D - (I) of this well I comes*
- NB. "well come-inf" is a LVC and means "to like".

**Comment by jnivre** [comment] 2016-02-16 11:09
Question about LVC (although we should probably start a new thread about this): Can "floor" be inflected in this usage? Can it take modifiers? Or is it frozen in combination with "eat" when it means "fall down"? If it is, then it should NOT be treated as a regular direct object. Then it is different from (most) English support verb constructions, which do allow modification and inflection:

She took a photo of the cathedral.
She took two photos of the cathedral.
She took a nice photo of the cathedral.

**Comment by spyysalo** [comment] 2016-02-16 11:25
I support @dan-zeman closing this issue and have opened #255 for discussion of LVCs.

**Comment by dan-zeman** [comment] 2016-02-16 12:13
@mojgan-seraji : I apologize for deliberately ignoring the dative arguments (subjects?) in Persian in my summary. Since the criteria for subjecthood differ across languages, I restricted myself to languages that are most closely related to Russian. Persian might have its own reasons for dative subjects and my not seeing them may as well just reflect my lack of knowledge of the language. Note however that for _Mr. President ARE here_ you could just extend the agreement rules by the feature of politeness. We have something similar in Czech when addressing a respected singular person: _you.Plur have.Plur been.Sing_. Your rules for subjecthood might also include something like "if one of the arguments of the verb is in nominative, then this is the subject".

**Comment by mojgan-seraji** [comment] 2016-02-16 15:10
@dan-zeman: I understand! No problem at all! Perhaps wrong thread for Persian. :)

I still believe that the structure of dative subjects in Persian is deeply tied to LVCs. That was my reason to bring this up in the same discussion. The LVC part was my starting point to get into dative subjects and what kind of grammatical criteria should be considered in identifying a subject.

**Comment by tsamardzic** [comment] 2016-10-14 10:33
@dan-zeman  
We have just started working on Serbian UD and we came across the issue of the distinction **dobj** vs. **iobj** right away. It seems to me that allowing **iobj** in the sentences where there are no **dobj** is necessary for Slavic languages. If not, then we will annotate differently **im**  in  

> im je žao onih prosvjednika

and **mi** in

> hladno mi je

(examples cited above) while they are grammatically identical. 

If this is a possibility, we could list some more concrete cases where **iobj** without a **dobj** annotation applies.

**Comment by KirilSimov** [comment] 2016-10-14 11:56
Dear All,

In our view we have to represent the difference between dobj and iobj
independently from their realization in a given sentence, because
the UD treebank could be accompanied with other resources like
valency lexicon where the difference (in case, for example) will be
presented. Thus, if a verb allows for an accusative dobj and a dative iobj
in a sentence with only iobj realized, it will be strange to call it dobj.

With best regards,

Kiril and Petya

**Comment by dan-zeman** [comment] 2016-10-14 18:56
I am not very happy with how UD v1 defines `dobj` and `iobj`, although I am not sure how the perfect solution should look like. I think our life might be easier with just a plain `obj`. _If_ `iobj` is understood as the addressee role with verbs of giving, then it would be natural to label this role `iobj` even when no other object is present. It is intuitive to understand `iobj` that way, but it seems to me that this is not how it was meant when originally defined in Stanford (@manning @mcdm).

@tsamardzic : In your example I am not yet convinced that the dative _mi_ is a core argument of the predicative. Is it obligatory in Serbian? Couldn't you also say a general statement like _hladno je_ "it is cold"? (You could in Czech.) If it is optional then maybe it is just `nmod`. (Although it is possible that my conversion of the Czech data does not comply with what I just said... I would have to check.)

In your other example, _im je žao onih prosvjednika_ lit. "to-them is sorry of-that protesters", the situation is different (probably – I am again projecting Czech to Serbian) and you cannot omit _im_, hence it is a core argument, i.e. `iobj`.

**Comment by olesar** [comment] 2016-10-15 01:25
@dan-zeman, @tanja, @KirilSimov we had a meeting with @jnivre on that topic in Russian and he convinced us that any second argument of the verb (marked with case) should be tagged as dobj in UD v1. So it looks like a PropBank style now, dobj/ARG1 being nouns in Acc, Ins, Dat, and Gen. At the same time, if we have ccomp/xcomp in the argument structure, then we assign iobj to the arguments in Ins and Dat. The predicative constructions are tagged just differently. We have examples likeМне стыдно за вас .I.Dat <--iobj-- am-ashamed.PRAEDIC for you .  since we label the infinitival argument of the predicative as its subj, cf.Мне странно так думать .I.Dat <--iobj-- it-is-strange.PRAEDIC --subj--> to-think so . (Sorry, I cannot remember now why we assign the Dative participant iobj and not dobj here. May be because we never have Acc in this position). @Dan, the Dative participant is the core argument of the predicative words from the semantic point of view (cf. the role of Experiencer), this has nothing to do with its syntactic optionality. Olga

**Comment by tsamardzic** [comment] 2016-10-17 12:56
Thanks everybody for your comments and explanations. 

@olesar :  It's good to know that you have already had a discussion on this with @jnivre. Is there maybe some documentation on the discussion? It would be very useful for us to go through the arguments. 

@dan-zeman : 
I agree with you that **mi/im**  is more easily omitted with _hladno_ than with _žao_, but this does not make the two constituents syntactically different. Consider, for example, English

> John ate this morning  
> vs. 
> John ate an apple this morning.

Just because you can omit a constituent doesn't mean it's a `nmod`. 

I think it would be important not to annotate differently things that are syntactically identical, especially if we do not have very good reasons for that. Could you maybe point me to some readings regarding the original Stanford definitions, so that I can check the reasons?

**Comment by jnivre** [comment] 2016-10-17 13:09
In addition to the universal guidelines for `dobj` and `iobj`, you can find some discussion of core arguments: http://universaldependencies.org/v2/core_dependents.html. Especially the section "Chris on iobj" is relevant to the discussion here.

**Comment by tsamardzic** [comment] 2016-10-19 13:30
Thanks @jnivre for pointing me to the relevant discussion. I completely agree with the idea of using  `iobj` to label all "other objects" and 

>  to regard these other objects as also core arguments

This makes a lot of sense in the case of Serbian. 

My concern is the following sentence in the [universal guidelines](http://universaldependencies.org/u/dep/iobj.html):

> In general, if there is just one object, it should be labeled dobj, regardless of the morphological case or semantic role that it bears.

As I think I show in the previous posts, applying this general principle as a strict rule leads to unwanted inconsistencies. I would like to argue for this sentence to be reformulated or excluded from the guidelines (at least for Serbian). 

In the universal  guidelines, this instruction is supported with an English example where we have two different objects, subject matter in 

> She teaches _introductory logic_

and recipients in:

>  She teaches _the first-year students_

The verb _teach_ in the sense realised in this example is equivalent to Serbian _predavati_, so a simplified translation would be 

> Ona 'she' predaje 'teaches' _logiku**ACC**_ 'logic'.

vs. 

> Ona 'she' predaje 'teaches' _studentima**DAT**_ 'students'.

I would say that _studentima**DAT**_ should NOT be `dobj`. Unlike English _the first-year students_, Serbian _studentima**DAT**_ does not participate in the passive alternation and does not show any other property of a direct object. I really do not see why we would annotate it as such. 

Would people agree that we go on and annotate such constituents as `iobj`?  We would certainly provide language-specific guidelines for this annotation.

**Comment by jnivre** [comment] 2016-10-19 14:28
The proposal for v2 is to use a general "obj" relation for both of these. I think this captures the essence of the original UD philosophy without being offensive to people who want to see a tighter association with case and/or semantic roles. See: http://universaldependencies.org/2016-09-05--06-prague/core-dependents.html

**Comment by olesar** [comment] 2016-10-19 23:33
In this context (and echoing the discussion at http://universaldependencies.org/v2/core_dependents.html), I am a bit worried about the assumption that PPs (prepositional / postpositional phrases) should be mostly tagged as nmod (aka anom/advnom in v2) in UD.
It is not uncommon that in many case-marking languages we would have a pattern like this for a number of synonymous verbs (teach 1,2,3):

> She teaches1/3 introductory logic (ACC)
> She teaches2/4 introductory logic (INS)

She teaches1 the first-year students (DAT)
She teaches2 the first-year students (ACC)
She teaches3 the first-year students (DAT/PP), with the preposition like "to" and "before"
She teaches4 the first-year students (PP), comitative

They all are definitely core arguments in terms of Fillmore's frame semantics and can be considered "semi-core" elements in some core-oblique theories. The problem is that there are hardly any good working formal criteria (word order, obligatoriness, topicalisation, etc., e.g. see table 2 in
http://users.ox.ac.uk/~cpgl0015/Arka_Core_oblique_distinction_and_core_index_in_some_Austronesian_languages.pdf#43
) in Slavic languages to draw the line between core and oblique elements. (And Nathan's suggestion here: 
http://www.cs.cmu.edu/~nschneid/prepv-slides.pdf, Slide 25
does not work as well).

Another well-known example is Theme and Goal motion verbs.
I think we should define the closed class of morphosyntactic devices and thematic roles to be prototypically "core" in Slavic languages and then talk about promotion and demotion to/from this syntactic status in the case of particular predicates and constructions.
The radical position to include only Accusative dependents in the core list (excluding temporal dependents) sounds a bit too radical to me.

Btw Joakim and Chrism, and Co, have you looked through the data of Martin Haspelmath's ValPal project (80 typical verb frames in 36 typologically different languages) while working on the core vs. oblique criteria?
http://valpal.info/about/project

**Comment by tsamardzic** [comment] 2016-10-20 06:43
General `obj` label works well for us. 

Just to come back to the starting topic of this thread, ~~we will use this label for "dative/logical subjects" too~~.  

Actually, following: 

> The notion of core argument is then reserved for dependents of the verb that exhibit all or most of this prototypical encoding. All other dependents of the verb are said to be oblique.

"dative/logical" subjects should be oblique, that is `advnom`.

Is this right?

**Comment by jnivre** [comment] 2016-10-20 10:14
@olesar This is definitely very tricky. Working out the application of the core-oblique distinction across different languages is going to be one of the major challenges in improving consistency under v2. One idea we have is that the universal guidelines for v2 will be organised by major construction types, instead of definitions of single relations, and use examples from many languages. I hope you are all interested in contributing to this documentation. Over time, I hope that a better understanding of how to apply these distinctions cross-linguistically will emerge.

**Closed as completed** 2023-11-15 21:48 UTC
Labels: a:bug, a:standard needed, b:dependencies, lang:Slavic
